---
title: "Time Series Regression and EDA"
output: html_document
---

```{r}
library(astsa)

help(salmon)
help(cmort)
help(tempr)
help(part)
```

Estimate the Linear Trend of a commodity
```{r}
salmon
length(salmon)
```

```{r}
plot(salmon,
     col = 4,
     ylab = "USD per KG",
     main = "Salmon Export Price")
```

```{r}
summary(fit <- lm(salmon ~ time(salmon),
                  na.action = NULL))
```

```{r}
tsplot(salmon,
       col = 4,
       ylab = "USD per KG",
       main = "Salmon Export Price")
```

Plot and visualize the data
```{r}
culer = c(rgb(0.66, 0.12, 0.85), rgb(0.12, 0.66, 0.85), rgb(0.85, 0.30, 0.12))

par(mfrow = c(3,1))

tsplot(cmort,
       main = "Cardiovascular Mortalitiy",
       col = culer[1],
       type = "o",
       pch = 19,
       ylab = "")

tsplot(tempr,
       main = "Temperature",
       col = culer[2],
       type = "o",
       pch = 19,
       ylab = "")

tsplot(part,
       main = "Particulates",
       col = culer[3],
       type = "o",
       pch = 19,
       ylab = "")
```

Plot them combined
```{r}
tsplot(cmort, 
       main = "",
       ylab = "",
       ylim = c(28, 138),
       col = culer[1])

lines(tempr,
      col = culer[2])

lines(part,
      col = culer[3])

legend("topright",
       legend = c("Mortality", "Temperature", "Pollution"),
       lty = 1,
       lwd = 2,
       col = culer,
       bg = 'white')
```

Now, put them in a correlation matrix.
```{r}
panel.cor <- function(x,y, ...) {
  usr <- par("usr"); on.exit(par(usr))
  par(usr = c(0,1,0,1))
  r <- round(cor(x,y), 2)
  text(0.5, 0.5, r, cex = 1.75)
}

pairs(cbind(Mortality = cmort,
            Temperature = tempr,
            Particulates = part),
      col = 4,
      lower.panel = panel.cor)
```

Another way of visually graphing it
```{r}
matt <- cbind(cmort,
              tempr,
              part)
cor(matt)
pairs(matt,
      col = 4)
```

```{r}
plot(tempr, tempr^2)
cor(tempr, tempr^2)
```

```{r}
tempr - mean(tempr)
tempr - mean(tempr)^2

k <- mean(tempr)
plot(tempr - k, (tempr - k)^2)
cor(tempr - k, (tempr - k)^2)
```

```{r}
temp = tempr - mean(tempr)
temp2 = temp^2
trend = time(cmort) # Trend line, abstract time series feature
fit = lm(cmort ~ trend + temp + temp2 + part,
         na.action = NULL)
summary(fit)
```

```{r}
summary(aov(fit))
```

```{r}
summary(aov(lm(cmort ~ cbind(trend,
                             temp,
                             temp2,
                             part))))
```

```{r}
num = length(cmort);

AIC(fit)/num - log(2*pi)
BIC(fit)/num - log(2*pi)
```

```{r}
temp = tempr - mean(tempr)
ded = ts.intersect(cmort,
                   trend = time(cmort),
                   temp,
                   temp2 = temp^2,
                   part,
                   partL4 = lag(part, -4))

summary(fit <- lm(cmort ~ trend + temp + temp2 + part + partL4,
                  data = ded))
```

```{r}
pairs(ded)
cor(ded)

AIC(fit)/nrow(ded) - log(2*pi)
BIC(fit)/nrow(ded) - log(2*pi)
```

